### ISSUE TITLE
Early Tasks: Start Here!

### ISSUE THREAD

**Issue by fourthedesign** [IsotopicIO/iso-space-game#5]
While we are working on ideas and features that will have a big impact on the game, it's important to focus on implementing basic things that will most probably not be nullified in the future.

## Here are some features that fit that criteria, and can be worked on by new contributors:
If you wish to take any of these on, please create an issue with it, or let us know on the discord to avoid conflicts of work.

**Programming:**

- (DONE) Collision detection: Make the ship collide with obstacles in the map segments. The game can just reset for now, until a UI menu arrives
- (DONE) Simple UI main menu
- (DONE) UI "HUD" during game
- Code optimization and organization: Better organize current code
- (DONE) Scoring system: Keep track of score and display score in UI
- Saving system: Store game progress and other data locally, encrypt/decrypt saved data.

**Game Design:**

- Feature ideas
- Concept art and ideas for game's art style, UI and models

**General:**
- Help write a proper contributing workflow
- Further details on contribution guidelines, readme and other docs
- Organize project folders

**Comment by fourthedesign** [comment]
Updated, 24/01/2023

**Comment by CyberDryad** [comment]
Added a simple canvas and HUD with in game timer

**Comment by fourthedesign** [comment]
Updated, 03/02/2023

**Comment by ANGELB3AR** [comment]
Added main menu scene with 'Play Game' button

**Comment by fourthedesign** [comment]
Closing this issue, as we have "finalized" the basic concept of gameplay, and moved on with bigger tasks. Will open new issue for available tasks.
